<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729155151 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE club (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE game_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, venue VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, score_home INT NOT NULL, score_away INT DEFAULT NULL, opponent_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, home_team_id INT NOT NULL, away_team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4868BC8A9C4C13F6 ON game_match (home_team_id)');
        $this->addSql('CREATE INDEX IDX_4868BC8A45185D02 ON game_match (away_team_id)');
        $this->addSql('CREATE TABLE match_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, minute INT NOT NULL, zone_x DOUBLE PRECISION NOT NULL, zone_y DOUBLE PRECISION NOT NULL, comment VARCHAR(255) DEFAULT NULL, related_player_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sync_status VARCHAR(255) NOT NULL, client_uuid VARCHAR(255) NOT NULL, game_match_id INT NOT NULL, player_id INT NOT NULL, tagged_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_85C47506E393C4 ON match_event (client_uuid)');
        $this->addSql('CREATE INDEX IDX_85C4750681FA53F0 ON match_event (game_match_id)');
        $this->addSql('CREATE INDEX IDX_85C4750699E6F5DF ON match_event (player_id)');
        $this->addSql('CREATE INDEX IDX_85C47506B0156D6A ON match_event (tagged_by_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, birth_date DATE DEFAULT NULL, position VARCHAR(255) NOT NULL, license_number VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A65296CD8AE ON player (team_id)');
        $this->addSql('CREATE TABLE player_season_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season VARCHAR(255) NOT NULL, goals INT NOT NULL, key_passes INT NOT NULL, minutes_played INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C04BC05799E6F5DF ON player_season_stats (player_id)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, season VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, club_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61F61190A32 ON team (club_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, club_id INT NOT NULL, team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D64961190A32 ON "user" (club_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649296CD8AE ON "user" (team_id)');
        $this->addSql('CREATE TABLE user_player (user_id INT NOT NULL, player_id INT NOT NULL, PRIMARY KEY (user_id, player_id))');
        $this->addSql('CREATE INDEX IDX_FD4B6158A76ED395 ON user_player (user_id)');
        $this->addSql('CREATE INDEX IDX_FD4B615899E6F5DF ON user_player (player_id)');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A9C4C13F6 FOREIGN KEY (home_team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_match ADD CONSTRAINT FK_4868BC8A45185D02 FOREIGN KEY (away_team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_event ADD CONSTRAINT FK_85C4750681FA53F0 FOREIGN KEY (game_match_id) REFERENCES game_match (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_event ADD CONSTRAINT FK_85C4750699E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE match_event ADD CONSTRAINT FK_85C47506B0156D6A FOREIGN KEY (tagged_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player_season_stats ADD CONSTRAINT FK_C04BC05799E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F61190A32 FOREIGN KEY (club_id) REFERENCES club (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64961190A32 FOREIGN KEY (club_id) REFERENCES club (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE user_player ADD CONSTRAINT FK_FD4B6158A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_player ADD CONSTRAINT FK_FD4B615899E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A9C4C13F6');
        $this->addSql('ALTER TABLE game_match DROP CONSTRAINT FK_4868BC8A45185D02');
        $this->addSql('ALTER TABLE match_event DROP CONSTRAINT FK_85C4750681FA53F0');
        $this->addSql('ALTER TABLE match_event DROP CONSTRAINT FK_85C4750699E6F5DF');
        $this->addSql('ALTER TABLE match_event DROP CONSTRAINT FK_85C47506B0156D6A');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65296CD8AE');
        $this->addSql('ALTER TABLE player_season_stats DROP CONSTRAINT FK_C04BC05799E6F5DF');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61F61190A32');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64961190A32');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649296CD8AE');
        $this->addSql('ALTER TABLE user_player DROP CONSTRAINT FK_FD4B6158A76ED395');
        $this->addSql('ALTER TABLE user_player DROP CONSTRAINT FK_FD4B615899E6F5DF');
        $this->addSql('DROP TABLE club');
        $this->addSql('DROP TABLE game_match');
        $this->addSql('DROP TABLE match_event');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE player_season_stats');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_player');
    }
}
